name: Build new image

on:
  schedule:
  # Run every weekday at 7am
  - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull image from Dockerfile.release
        run: |
          ./docker-buildx.sh
